# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CsNWxS2npfi6Z0xsllJtZKQdoLi55JM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path1 = "matches.csv"
file_path2="deliveries.csv"
# Load the latest version
df_matches = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yash9439/ipl-dataset",
  file_path1,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df_deliveries = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yash9439/ipl-dataset",
  file_path2,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 matches records:", df_matches.head())
print("*"*100)
print("First 5 deliveries records:", df_deliveries.head())

df_matches.shape

df_deliveries.shape

df_matches

print(df_deliveries.head(20))

df_matches.columns

df_deliveries.columns

df_deliveries.isnull().sum()

df = df_deliveries.merge(df_matches[['id','team1','team2']],
                        left_on='match_id', right_on='id')

df.shape

df

df_deliveries.columns

df.columns

# p
df['team_runs'] = df.groupby(['match_id','batting_team'])['total_runs'].cumsum()

# p
df['team1_runs'] = df.apply(
    lambda x: x['team_runs'] if x['batting_team'] == x['team1'] else None,
    axis=1
)

df['team2_runs'] = df.apply(
    lambda x: x['team_runs'] if x['batting_team'] == x['team2'] else None,
    axis=1
)

# p
df[['team1_runs','team2_runs']] = df.groupby('match_id')[['team1_runs','team2_runs']].ffill().fillna(0)

df

df_deliveries.columns

df['is_wicket']=df['player_dismissed'].notna().astype(int)

# df_deliveries=df_deliveries.drop(columns=['is_super_over', 'wide_runs',
#        'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
#        'batsman_runs', 'extra_runs','player_dismissed',
#        'dismissal_kind', 'fielder'])

df.columns

def unique_(x):
  print(x.unique())

df.info()

df=df.drop(columns=['is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
        'extra_runs', 'total_runs',
        'fielder', 'id'])

df

# p
df['target'] = np.where(df['inning'] == 1, 0, df['team1_runs'] + 1)

# p
df['runs_to_win'] = np.where(df['inning']==1,0,df['target'] - df['team_runs'])

df['balls_bowled'] = ((df['over'] - 1) * 6) + df['ball']
# p

# p
balls_remaining     = (20 * 6) - df['balls_bowled']

df['curr_run_rate'] = np.where(
    df['balls_bowled'] == 0, 0.0,
    (df['team_runs'] * 6) / df['balls_bowled']
)

df['req_run_rate']  = np.where(
    balls_remaining == 0, np.inf,
    (df['runs_to_win'] * 6) / balls_remaining
)

df['crr_rrr_ratio'] = df['curr_run_rate'] / df['req_run_rate'].replace(0, np.inf)
df.loc[df['inning'] == 1, ['target', 'runs_to_win', 'req_run_rate', 'crr_rrr_ratio']] = 0

df['balls_remaining'] = (20 * 6) - df['balls_bowled']

df['total_wickets']=df.groupby(['match_id','inning'])['is_wicket'].cumsum()

df['batsman_run_cum']=df.groupby('batsman')['batsman_runs'].cumsum()
df['balls_faced_cum']=df.groupby('batsman').cumcount()+1
df['strike_rate']=df['batsman_run_cum']/df['balls_faced_cum']*100

df['is_out']=(df['player_dismissed']==df['batsman']).astype(int)
df['batsman_outs_com']=df.groupby('batsman')['is_out'].cumsum()
# 1. Define your Universal Numbers (The "Prior")
# Let's assume a standard player has 50 runs and 2 outs
universal_runs = 50
universal_outs = 2

# 2. Calculate the Smoothed Average
# We add the universal numbers to the player's actual cumulative stats
df['batting_average'] = (df['batsman_run_cum'] + universal_runs) / (df['batsman_outs_com'] + universal_outs)

# 3. Do the same for Strike Rate
# Assume a standard player scores 100 runs in 80 balls (125 SR)
universal_sr_runs = 100
universal_balls = 80

df['strike_rate'] = ((df['batsman_run_cum'] + universal_sr_runs) / (df['balls_faced_cum'] + universal_balls)) * 100

# 1. Calculate actual cumulative stats
df['bowler_runs_conceded'] = df.groupby('bowler')['batsman_runs'].cumsum()
df['bowler_balls_bowled'] = df.groupby('bowler').cumcount() + 1
df['bowler_wickets_cum'] = df.groupby('bowler')['is_wicket'].cumsum()

# 2. Apply Universal Smoothing (The "Starting Credit")
# Economy = (Runs / Balls) * 6
df['exp_bowler_eco'] = ((df['bowler_runs_conceded'] + 300) / (df['bowler_balls_bowled'] + 240)) * 6

# Bowling Average = Total Runs / Total Wickets
df['exp_bowler_avg'] = (df['bowler_runs_conceded'] + 300) / (df['bowler_wickets_cum'] + 10)

df.columns

# 1. Merge the 'winner' column from matches into your main df
df = df.merge(df_matches[['id', 'winner','city']], left_on='match_id', right_on='id', how='left')

# 2. Create the 'result' column: 1 if batting team won, else 0
# We use np.where for speed
df['result'] = np.where(df['batting_team'] == df['winner'], 1, 0)
df.drop(columns=['id', 'winner'], inplace=True)
# 4. Quick check to see the results
print(df[['batting_team', 'match_id', 'result','city']].head())

df

df.columns

lis = [
    'match_id', 'non_striker', 'player_dismissed', 'dismissal_kind',
    'team1', 'team2',
    'is_wicket',
    'over', 'ball',
    'batsman_runs',
    'batsman_run_cum',
    'balls_faced_cum',
    'is_out',
    'batsman_outs_com',
    'bowler_runs_conceded',
    'bowler_balls_bowled',
    'bowler_wickets_cum',
    'team_runs', 'team1_runs', 'team2_runs',
    'balls_bowled',
    'target'
]
df = df.drop(columns=lis)

df.info()

y=df['result']
df=df.drop(columns=['result'])

df.describe()

df

# 1. Fix Required Run Rate: If balls are 0, set a high cap (like 50) or 0
df['req_run_rate'] = df['req_run_rate'].replace([np.inf, -np.inf], 50)

# 2. Fix the Ratio: If RRR was 0 or inf, the ratio might be broken
df['crr_rrr_ratio'] = df['crr_rrr_ratio'].replace([np.inf, -np.inf], 0)

# 3. Double check for any NaNs created during calculation
df.dropna(subset=['batting_average', 'exp_bowler_eco', 'strike_rate'], inplace=True)

from sklearn.model_selection import train_test_split
x_train,x_temp,y_train,y_temp=train_test_split(df, y, test_size=0.4, random_state=42)
x_cv,x_test,y_cv,y_test=train_test_split(x_temp, y_temp,test_size=0.5, random_state=42)

df.columns

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder,TargetEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
target_encode=['batsman','bowler']
nominal_cols=['batting_team','bowling_team','city']
numeric_cols=['runs_to_win', 'curr_run_rate', 'req_run_rate', 'crr_rrr_ratio',
              'balls_remaining', 'total_wickets', 'strike_rate', 'batting_average',
              'exp_bowler_eco', 'exp_bowler_avg']
print("Infinite values remaining:", np.isinf(df[numeric_cols]).values.sum())
preprocessing=ColumnTransformer(transformers=[
    ('nominal',OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),nominal_cols),
    ('target',TargetEncoder(),target_encode),
    ('scalar',StandardScaler(),numeric_cols)
])

pipe=make_pipeline(preprocessing,LogisticRegression(max_iter=1000))

pipe.fit(x_train,y_train)

proba_cv=pipe.predict(x_cv)

proba_train=pipe.predict(x_train)

proba_test=pipe.predict(x_test)

from sklearn.metrics import roc_auc_score,f1_score,accuracy_score
print(accuracy_score(proba_cv,y_cv))
print(accuracy_score(proba_train,y_train))
print(accuracy_score(proba_test,y_test))

from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from xgboost import XGBClassifier
voting_clf=VotingClassifier(estimators=[
    ('rf',RandomForestClassifier()),
     ('lr',LogisticRegression()),
    ('XG',XGBClassifier())])

voting_pipe=make_pipeline(preprocessing,voting_clf)

from sklearn.model_selection import RandomizedSearchCV
param_dict={
    'votingclassifier__XG__n_estimators': [100, 200, 300],
    'votingclassifier__XG__max_depth': [3, 5, 7],
    'votingclassifier__XG__learning_rate': [0.1, 0.01, 0.001],
    'votingclassifier__rf__n_estimators': [100, 200, 300]
}
random_search=RandomizedSearchCV(estimator=voting_pipe,param_distributions=param_dict,n_iter=5,cv=3,verbose=2,n_jobs=-1)
random_search.fit(x_train,y_train)

best_estimator=random_search.best_estimator_
print("Best_Parameters ",random_search.best_params_)
print("Best_Estimator",best_estimator)

test1=best_estimator.predict(x_test)
test2=best_estimator.predict(x_train)
test3=best_estimator.predict(x_cv)

print(accuracy_score(test3,y_cv))
print(accuracy_score(test2,y_train))
print(accuracy_score(test1,y_test))